### ISSUE TITLE
LineStyles.dyf - does not work with doc and link

### ISSUE THREAD

**Issue by Denver-22** [aussieBIMguru/Crumple#3]
This node only works on the current document.
Does not work with another document or link (package 2022.5.27 also):
"Traceback (most recent call last):
  File "<string>", line 44, in <module>
ValueError..."
![LineStyle](https://user-images.githubusercontent.com/44049465/170661814-5434993d-7193-4281-8e8a-6f67e04c5381.PNG)
Please check node

**Comment by aussieBIMguru** [comment]
I have tested this with a linked instance in 2022 and it is working for me. I am not sure what the Python script is doing there, but I tested out my nodes with this in the screenshot attached. Noting I did not use archilab to get the document, I just selected the link instance as a model element and gave it to revit.getdocument.

![testing](https://user-images.githubusercontent.com/58870499/170664196-c8d3c9bb-a369-4672-aa00-ef7865700dda.PNG)

**Comment by Denver-22** [comment]
Thanks for the answer. I did as you - does not work in Revit 2019. Found another way...

**Comment by aussieBIMguru** [comment]
Ah yes unfortunately I can't guarantee functionality in builds pre-Revit 2020, as I build in 2020 and test in 2021/2022 currently. They've added quite a few new aspects to Dynamo in later builds so the older the build is the less likely some custom nodes will work in most newer packages.
