### ISSUE TITLE
Possible to add option to remove span direction to Floors.Create

### ISSUE THREAD

**Issue by BrenJozi** [aussieBIMguru/Crumple#5]
Not really an issue but more of a request for an addition/edit.

Would it be possible to add a Boolean to Floors.Create to use/not use a span direction line when creating a floor? When a floor is made with a span direction as a line, there are problems with groups exploding once the floor is added. If the line is removed there are no issues.

**Comment by aussieBIMguru** [comment]
Unfortunately as far as I can tell there isn't a way to achieve this in the floor creation process. I can find methods in the API to get slope/span direction but not one to choose a sketch line.

I believe if you set load bearing to false after making the floor this should remove a span direction option. See this thread for an example:

https://forum.dynamobim.com/t/removing-the-span-direction-after-floor-by-room-boundary-span-direction-causing-havoc-in-groups/82130/21
