### ISSUE TITLE
Dynamo.Exceptions.LibraryLoadFailedException

### ISSUE THREAD

**Issue by Daralice** [aussieBIMguru/Crumple#6]
Revit: 2022.1.0.4
Dynamo: 2.12.0.5650
Crumple: 2022.5.27

Hi! 😄 

I got a question with your package.
Last friday I got this error out of nowhere and I dont know where it comes from:

![image](https://github.com/aussieBIMguru/Crumple/assets/118201315/885078ba-82a0-4331-9b03-c781dce5d50d)

Do you have an idea how I could solve this?

Kind regards,

Daralice

**Comment by aussieBIMguru** [comment]
No idea unfortunately.

I believe they've added some security checks in later builds but haven't
been updating my package in higher builds. As far as I know we don't have
the ability to sign dll's in Dynamo unless we use C# (which I don't).

Regards,

Gavin Crump
Content Creator
Aussie BIM Guru



*Youtube: *Link here
<https://www.youtube.com/channel/UCry22yTdpgEDdzIZig7NSMQ?>
*LinkedIn: *Link here <https://www.linkedin.com/in/gavincrump/>
*Twitter:* @AussieBIMGuru <https://twitter.com/aussiebimguru>

**Comment by Daralice** [comment]
Thank you!

My collegue found out that if we use the older version of Crumple (2022.2.13) it does work for her.
I'll try this and hopefully I can use it for my graphs again. Your tutorials help us so much with our work. 😄

**Comment by Daralice** [comment]
It works! 😄

**Comment by Daralice** [comment]
Nevermind. As soon as I run my skript the error reoccurs. 😭

**Comment by Daralice** [comment]
This helped:
https://forum.dynamobim.com/t/dynamo-packages-not-loading-2-12/79904

I don't know how the package got in the wrong folder, but now it works. 😄
